version: '3.3'

services:

  web:
    build: ./api/
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./api/:/usr/src/app
    ports:
      - 8004:8000

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: ng serve --host 0.0.0.0
    volumes:
      - './frontend/:/usr/src/fronted/'
      - '/usr/src/fronted/node_modules'
    ports:
      - '4201:4200'